### ISSUE TITLE
Freeze and potential crash when opening grid with large amount of items

### ISSUE THREAD

**Issue by kibmcz** [badasintended/slotlink#20]
**Setup**
- Minecraft: 1.16.1
- Fabric API: 0.90+BUild.204
- slotlink: 1.0
- related mod: VERSION

**Problem**
Opening grid via Storage Remote or Storage Request when the storage network stores more than a certain amount of items has a delay freezing game (will crash it if you interact with window during the delay). 
Crash report: _if any, upload it on paste website and copy the link._

**Reproduction**
Setup a chest storage array of at least 100 chests and link them, use import bus to import cobble from multiple cobble gens provided by Convenient Things accelerated by a compressed Torcherino.

When cobble exceeds 200k the freezing will start to happen.

![2020-07-31_22 31 59](https://user-images.githubusercontent.com/857986/89094184-65792680-d37e-11ea-850d-318587061549.png)

**Remarks**
Mods used to reproduce it are https://www.curseforge.com/minecraft/mc-mods/torcherino/, https://www.curseforge.com/minecraft/mc-mods/convenient-things/ optional https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric

**Comment by deirn** [comment]
hmm, are you manually downloaded Spinnery from CF? if so, please use the newest version (or don't manually download since slotlink already ships with it). I saw some NullPointerException that will cause a crash on older spinnery but now try-catched and shows some error instead. The amount of NPEs should be reduced in slotlink-1.0.1.

on another note, FPS slows down is expected when opening the Request terminal because the server needs to send **all stack** to the client to sync it. It doesn't appear to affect server TPS though so it's all good.
![2020-08-01_13 24 38](https://user-images.githubusercontent.com/21150434/89096644-6358ab80-d402-11ea-8914-a709f0ac7ff3.png)
_the red bar is when I opened the Storage Request_

I know when you have some mods like this you really want to make a big, I mean, a HUGE network, I know cuz I'm the same. But please start with little and add more chest when necessary :P.

**Comment by kibmcz** [comment]
I made sure to note any bundled mods and not install them so that wasn't causing a issue. What's interesting is on the pre 1.0 builds the delay was minor but afterwards on same (overkill) storage set was the load was worse.  

Hmm yea down scaled set of  higher capacity chests with some barrels from stockpile for 'offline'  overflow storage will have to be done.

Thanks for the efforts tho :)

**Comment by deirn** [comment]
yeah, unfortunately, I need to manually sync stacks between server-client or otherwise the remote only works when the chunk is between render distance. also #1 :v.

**Comment by kibmcz** [comment]
With #21 fixed a related issue that's tied to this issue. Not sure if this its own issue or related to this issue.

Triggers with delayed grid opening is done while exporting to another inventory with export cable.
[crash-2020-08-01_15.14.23-server.txt](https://github.com/badasintended/slotlink/files/5011273/crash-2020-08-01_15.14.23-server.txt)

**Comment by deirn** [comment]
Alright, found a way to reduce the delay. That is using the new screen handler API :v.

Opening a network of 126 vanilla chests, about 3/4 full
| 1.0.2 | 1.0.3 |
| - | - |
| ![2020-08-02_10 27 59](https://user-images.githubusercontent.com/21150434/89124617-92eedd00-d502-11ea-91b5-a1a8fdfca001.png) | ![2020-08-02_20 30 41](https://user-images.githubusercontent.com/21150434/89124626-9f733580-d502-11ea-848a-b2cb61df7231.png) |
| _no... you can't just need 1 second to load while I need 23 :sob:_ | _haha optimization go brr_|

For the stockpile crash, it looks like it tricks the check to think that the slot is always empty, regardless of item count, unless it is completely full. So I need to transfer the item one by one, in a loop. Should also be fixed in 1.0.3.

**Comment by kibmcz** [comment]
Impressive work that works great now :) 

![2020-08-02_15 57 01](https://user-images.githubusercontent.com/857986/89133425-eea47080-d4d8-11ea-8e42-182f3766c5e4.png)

**Comment by deirn** [comment]
closed in 2.0 :tada:
