### ISSUE TITLE
Filtered Link Cables

### ISSUE THREAD

**Issue by Adirelle** [badasintended/slotlink#25]
Hello,

Would you consider the following enhancement?

1. Allow to define filters to accept/reject items on Link cable.
2. Those filters would be checked for storing as well for counting and retrieving items.

Main use case: to store specific items in dedicated containers. This could be very useful with mods that provide new containers, like Storage Cabinet or Stockpile.

**Comment by deirn** [comment]
Filter are nice, i'll see what i can.

On another note, I gave up trying to make drawer style container to work on storage request. Most of the time they "trick" the check to think it's always empty/full depending you're inserting/taking item, there's no actual "slot" like in traditional inventory too (see #8, #21). They aren't intended to be used like normal chest (in gui) anyway. You can still import/export from it though.

**Comment by Adirelle** [comment]
> On another note, I gave up trying to make drawer style container to work on storage request. Most of the time they "trick" the check to think it's always empty/full depending you're inserting/taking item, there's no actual "slot" like in traditional inventory too (see #8, #21). They aren't intended to be used like normal chest (in gui) anyway. You can still import/export from it though.

It actually kinda work: slotlink shows one stack of each item in a stockpile barrel and I can extract them using a link cable, but as you said, it will not put them back.

BTW, I think hoppers properly work with stockpile barrels and I have seen another mod (https://github.com/BRForgers/Ducts, IIRC) that uses hopper's code to insert items into inventories.

**Comment by deirn** [comment]
> slotlink shows one stack of each item

and only one stack, since stockpile only reports one, [see this method](https://github.com/branchpanic/stockpile/blob/eea85a487ebe3c33566f5244d83e28a5ced3e400/src/main/kotlin/me/branchpanic/mods/stockpile/impl/attribute/FixedMassItemInv.kt#L43). It also has two slots, one that can't be inserted to.

it also always returns as if it's empty unless it's completely full. Hopper works because it moves one item at a time. [I need to loop to make it compatible because of this.](https://github.com/badasintended/slotlink/blob/c2562bf8b64e643e27faf069fa321de68784058c/src/main/kotlin/badasintended/slotlink/common/util/Utils.kt#L119)

if I really want to make it compatible, I need to hardcode it, but no I don't want to, sorry.

**Comment by Adirelle** [comment]
> It also has two slots, one that can't be inserted to.

Yes, they are labelled INBOUND_SLOT and OUTBOUND_SLOT, which is quite self-explanatory. I'm not used to Kotlin nor minecraft mod development. However, I code for a living and know several other languages, including Java. Maybe should I give it a try. What I miss is a reference documentation about the net.minecraft package and its interfaces. Is there some such doc somewhere ?

**Comment by deirn** [comment]
yarn is what you're looking for then. you need to setup a minecraft dev-env for it https://fabricmc.net/wiki/tutorial:setup
