### ISSUE TITLE
Crafting problem in the Storage request block

### ISSUE THREAD

**Issue by charlyb01** [badasintended/slotlink#44]
**Setup**
- Minecraft: 1.16 VERSIONS
- Fabric API: 1.16 VERSIONS
- slotlink: 1.16 VERSIONS
- related mod: XP Storage (and any other mod that requires the same thing that I'll explain)

**Problem**
Basically you can craft an item with XP Storage mod that is fully damaged when craft. This is done with the Item.onCraft() minecraft function. The problem is that when you craft the item on the crafting screen of the storage request block, it doesn't call this function (and so the item is crafted without any damage).

**Reproduction**
I guess it's clear enough, no need of reproduction.

**Remarks**
I tried to find out how you could solve this. I didn't figured it out yet but I'll let you know if I find. But I guess it's something related to ScreenHandlerType, maybe because yours isn't registered as a CraftingScreenHandler, something like that...

**Comment by deirn** [comment]
since it's spinnery :hahayes:, [i need to call it myself and try to mimic vanilla slot as best as I could](https://github.com/badasintended/slotlink/blob/1.16.2/src/main/kotlin/badasintended/slotlink/gui/widget/WCraftingResultSlot.kt).

![2020-08-30_16 27 20](https://user-images.githubusercontent.com/21150434/91655837-0d008a80-eade-11ea-99c3-d30cbe485ebb.png)

**Comment by charlyb01** [comment]
Oh yes okay haha! Thanks for changing your crafting method, you're the bro ;)
