### ISSUE TITLE
Reposition "Restock/Move all from/to network" buttons for mod compatibility

### ISSUE THREAD

**Issue by calloatti** [badasintended/slotlink#79]
Could you please move up or left a bit the "Restock/Move all from/to network" buttons so they dont overlap with the https://www.curseforge.com/minecraft/mc-mods/inventory-sorting sort button?

![image](https://user-images.githubusercontent.com/12817862/116126121-a51a3800-a69c-11eb-9a24-ce4d91088634.png)

**Comment by deirn** [comment]
It looks like kyrptonaught added a [default blacklist](https://github.com/kyrptonaught/Inventory-Sorter/blob/fd7f1e5ac057a095d2f5f7805eac5957acc9c0b3/src/main/java/net/kyrptonaught/inventorysorter/client/config/IgnoreList.java#L49) that has slotlink screen in it but it's not applied. I opened an issue there https://github.com/kyrptonaught/Inventory-Sorter/issues/47.
I'm not really recommending you to use inv sorter in request screen since it may breaks stuff

**Comment by calloatti** [comment]
The inventory sorter button above the player inventory only sorts the player inventory. For other containers, there is a separate sort button at the top of the container inventory, like chests for example.

**Comment by deirn** [comment]
![2021-05-08_21 06 18](https://user-images.githubusercontent.com/21150434/117542085-51ff9800-b041-11eb-9fd0-09d1a70667e1.png)
